### ISSUE TITLE
[LUA] Resolve invalid states/locations

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#207]
Currently two characters have unique issues:
1) Arachne - Was "killed", but did not "die" (transform to ghost/port).  Character is now unable to login.  Suggest some sort of login script solution to resolve this state.

2) Manslave - Was "killed", did "die".  Death relocates player to edge of map boundary inside a wall.  Correct spawn coordinates are 23, 19 (will retest once map is accessible)

**Comment by baughj** [comment]
Both seem to be related to legend errors

```
2020-06-12 22:40:08.254 -07:00 [ERR] EXCEPTION IN HANDLING: 0x03: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Hybrasyl.Legend.RegenerateIndex() in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/Legend.cs:line 96
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Hybrasyl.SampleStackExchangeRedisExtensions.Deserialize[T](Byte[] stream) in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/World.cs:line 73
   at Hybrasyl.SampleStackExchangeRedisExtensions.Get[T](IDatabase cache, String key) in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/World.cs:line 49
   at Hybrasyl.World.TryGetUser(String name, User& userobj) in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/World.cs:line 173
   at Hybrasyl.Login.PacketHandler_0x03_Login(Client client, ClientPacket packet) in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/Login.cs:line 101
   at Hybrasyl.Client.FlushReceiveBuffer() in /var/lib/jenkins/workspace/DeployHybrasylServer/hybrasyl/Client.cs:line 526
```

**Comment by Caeldeth** [comment]
Arachne has added legends via /legend command, but manslave does not

**Comment by baughj** [comment]
`Y` vs `y` in xml hilariously for manslave

**Comment by Caeldeth** [comment]
Having thought on this some more - existing issues with those two characters aside, are there any checks for invalid location/states on login?  Should there be?

**Comment by Caeldeth** [comment]
This was actually not an issue, was side effect of different issue.  Closed.
